# Kubernetes Service & Deployment file
apiVersion: v1
kind: Service
metadata:
  name: caddy-lab-svc
spec:
  type: NodePort
  selector:
    app: caddy
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-lab
  labels:
    app: caddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - image: IMAGE/NAME
        name: caddy-lab
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
